version: '3.9'

services:
  codice-fiscale-71:
    build: docker/php-7.1
    container_name: codice-fiscale-php-71
    working_dir: /app
    tty: true
    volumes:
      - .:/app:cached

  codice-fiscale-80:
    build: docker/php-8.0
    container_name: codice-fiscale-php-80
    working_dir: /app
    tty: true
    volumes:
      - .:/app:cached
